# Generated by Django 3.1.3 on 2020-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='discription',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='discription',
            field=models.TextField(max_length=1000),
        ),
    ]
