# Generated by Django 3.1.3 on 2020-12-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0007_auto_20201206_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
