# Generated by Django 3.1.3 on 2020-12-16 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0010_auto_20201216_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikesby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='dislike_users',
            field=models.ManyToManyField(related_name='disliked_posts', through='query.Dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
